package com.smartparking.common.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    AUTH_INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    AUTH_ACCOUNT_LOCKED(HttpStatus.FORBIDDEN),
    AUTH_ACCOUNT_NOT_ACTIVE(HttpStatus.FORBIDDEN),
    AUTH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    AUTH_REFRESH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    OTP_INVALID(HttpStatus.BAD_REQUEST),
    OTP_EXPIRED(HttpStatus.BAD_REQUEST),
    VEHICLE_NOT_FOUND(HttpStatus.NOT_FOUND),
    VEHICLE_ACCESS_DENIED(HttpStatus.FORBIDDEN),
    VEHICLE_INACTIVE(HttpStatus.CONFLICT),
    VEHICLE_BOOKING_TIME_CONFLICT(HttpStatus.CONFLICT),
    PARKING_LOT_NOT_FOUND(HttpStatus.NOT_FOUND),
    PARKING_LOT_NOT_ACTIVE(HttpStatus.CONFLICT),
    PARKING_LOT_ACCESS_DENIED(HttpStatus.FORBIDDEN),
    PARKING_LOT_UNSUPPORTED_VEHICLE_TYPE(HttpStatus.CONFLICT),
    PARKING_CAPACITY_INVALID(HttpStatus.CONFLICT),
    BOOKING_NOT_FOUND(HttpStatus.NOT_FOUND),
    BOOKING_ACCESS_DENIED(HttpStatus.FORBIDDEN),
    BOOKING_INVALID_STATE(HttpStatus.CONFLICT),
    BOOKING_TIME_INVALID(HttpStatus.BAD_REQUEST),
    BOOKING_CAPACITY_NOT_AVAILABLE(HttpStatus.CONFLICT),
    BOOKING_CANNOT_CANCEL(HttpStatus.CONFLICT),
    BOOKING_CANNOT_EXTEND(HttpStatus.CONFLICT),
    BOOKING_ALREADY_PROCESSED(HttpStatus.CONFLICT),
    PAYMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    PAYMENT_ALREADY_COMPLETED(HttpStatus.CONFLICT),
    PAYMENT_PROVIDER_ERROR(HttpStatus.BAD_GATEWAY),
    PAYMENT_SIGNATURE_INVALID(HttpStatus.UNAUTHORIZED),
    REFUND_AMOUNT_INVALID(HttpStatus.BAD_REQUEST),
    QR_CODE_INVALID(HttpStatus.BAD_REQUEST),
    QR_CODE_EXPIRED(HttpStatus.BAD_REQUEST),
    CHECK_IN_NOT_ALLOWED(HttpStatus.CONFLICT),
    CHECK_OUT_NOT_ALLOWED(HttpStatus.CONFLICT),
    VEHICLE_CONDITION_REQUIRED(HttpStatus.BAD_REQUEST),
    RESOURCE_VERSION_CONFLICT(HttpStatus.CONFLICT),
    IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT),
    ADMIN_REASON_REQUIRED(HttpStatus.BAD_REQUEST),
    AUDIT_LOG_NOT_FOUND(HttpStatus.NOT_FOUND),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }
}
