services:
  postgres:
    image: postgres:16-alpine
    container_name: smart-parking-postgres
    environment:
      POSTGRES_DB: smart_parking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12131415
    ports:
      - "5433:5432"
    volumes:
      - smart_parking_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smart_parking"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: smart-parking-redis
    ports:
      - "6379:6379"
    volumes:
      - smart_parking_redis:/data

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: smart-parking-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - smart_parking_minio:/data

volumes:
  smart_parking_postgres:
  smart_parking_redis:
  smart_parking_minio:
